# Generated by Django 2.1.2 on 2019-02-28 13:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task_Logs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logs', models.TextField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now=True, db_index=True)),
            ],
            options={
                'verbose_name_plural': 'Task Logs Table',
                'db_table': 'task_logs_tbl',
            },
        ),
        migrations.CreateModel(
            name='Task_Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('via_email', models.BooleanField(db_index=True, default=False)),
                ('via_popup', models.BooleanField(db_index=True, default=False)),
                ('created_on', models.DateTimeField(auto_now=True, db_index=True)),
                ('notified_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notified_to', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Task Notification Table',
                'db_table': 'task_notification_tbl',
            },
        ),
        migrations.CreateModel(
            name='Task_Observer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now=True, db_index=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('observer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Task Observers Table',
                'db_table': 'task_observers_tbl',
            },
        ),
        migrations.CreateModel(
            name='Task_Partipant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now=True, db_index=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('participant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participant', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Task Participants Table',
                'db_table': 'task_participants_tbl',
            },
        ),
        migrations.CreateModel(
            name='Task_Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.TextField()),
                ('details', models.TextField(blank=True, null=True)),
                ('deadline', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('high_priority', models.BooleanField(db_index=True, default=False)),
                ('email_notification', models.BooleanField(db_index=True, default=False)),
                ('remind', models.BooleanField(db_index=True, default=False)),
                ('repeat', models.BooleanField(db_index=True, default=False)),
                ('created_on', models.DateTimeField(auto_now=True, db_index=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('responsible_person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_person', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Task Table',
                'db_table': 'task_tbl',
            },
        ),
        migrations.AddField(
            model_name='task_partipant',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Task_Table'),
        ),
        migrations.AddField(
            model_name='task_observer',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Task_Table'),
        ),
        migrations.AddField(
            model_name='task_notification',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Task_Table'),
        ),
        migrations.AddField(
            model_name='task_logs',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Task_Table'),
        ),
    ]
