# Generated by Django 2.1.2 on 2019-03-06 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task_table',
            name='completed',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
