# Generated by Django 2.2 on 2019-07-05 21:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_task_table_completed'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Task_Partipant',
            new_name='Task_Participant',
        ),
        migrations.CreateModel(
            name='Task_Notification_Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notify_observer', models.BooleanField(db_index=True, default=False)),
                ('notify_observer_by', models.BooleanField(db_index=True, default=False)),
                ('notify_participant', models.BooleanField(db_index=True, default=False)),
                ('notify_participant_by', models.BooleanField(db_index=True, default=False)),
                ('notify_24_hrs_ago', models.BooleanField(db_index=True, default=False)),
                ('notify_once_everyday', models.BooleanField(db_index=True, default=False)),
                ('stop_after_deadline', models.BooleanField(db_index=True, default=False)),
                ('enable_observer_reply', models.BooleanField(db_index=True, default=False)),
                ('enable_participant_reply', models.BooleanField(db_index=True, default=False)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Task_Table')),
            ],
            options={
                'verbose_name_plural': 'Task Notification Settings Table',
                'db_table': 'task_notification_settings_tbl',
            },
        ),
    ]
